import { lazy } from 'react';

const QQPet13 = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "QQ Pet 13": {
    header: {
      icon: '/games/QQPet13/logo.png',
      title: 'QQ Pet 13',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: QQPet13,
    defaultSize: {
      width: 890,
      height: 530,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "qqPet13": {
    icon: '/games/QQPet13/logo.png',
    title: 'QQ Pet 13',
    component: QQPet13,
  },
  },
  catalogTargets: {
    "qqPet13": "QQ Pet 13"
  },
  categories: {
    "QQ Pet 13": "game"
  },
};
