import { lazy } from 'react';

const QQArcade = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "QQ Arcade": {
    header: {
      icon: '/games/QQArcade/icon.png',
      title: 'QQ Arcade',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: QQArcade,
    defaultSize: {
      width: 900,
      height: 650,
    },
    defaultOffset: {
      x: 80,
      y: 30,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "qqArcade": {
    icon: '/games/QQArcade/icon.png',
    title: 'QQ Arcade',
    component: QQArcade,
  },
  },
  catalogTargets: {
    "qqArcade": "QQ Arcade"
  },
  categories: {
    "QQ Arcade": "game"
  },
  startMenu: {
    "qqArcade": {
    type: 'program',
    appKey: 'QQ Arcade',
    icon: '/games/QQArcade/icon.png',
    title: 'QQ Arcade',
    description: '29 classic mini-games',
  },
  },
};
