import { lazy } from 'react';

const Diablo = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Diablo": {
    header: {
      icon: '/icons/games/diablo.png',
      title: 'Diablo',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Diablo,
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 120,
      y: 60,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "diablo": {
    icon: '/icons/games/diablo.png',
    title: 'Diablo',
    component: Diablo,
  },
  },
  catalogTargets: {
    "diablo": "Diablo"
  },
  categories: {
    "Diablo": "game"
  },
};
