import { lazy } from 'react';

const Messenger = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Windows Messenger": {
    header: {
      icon: '/icons/xp/messenger.png',
      title: 'Windows Messenger',
      buttons: ['minimize', 'close'],
    },
    component: Messenger,
    defaultSize: {
      width: 218,
      height: 434,
    },
    defaultOffset: {
      x: 110,
      y: 110,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "messenger": {
    icon: '/icons/xp/messenger.png',
    title: 'Windows Messenger',
    component: Messenger,
  },
  },
  catalogTargets: {
    "messenger": "Windows Messenger"
  },
  categories: {
    "Windows Messenger": "internet"
  },
  startMenu: {
    "messenger": {
    type: 'program',
    appKey: 'Windows Messenger',
    icon: '/icons/xp/messenger.png',
    title: 'Windows Messenger',
    description: 'Instant messaging',
  },
  },
};
