import { lazy } from 'react';

const XPTour = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Windows XP Tour": {
    header: {
      icon: '/icons/xp/tray/xptour.png',
      title: 'Windows XP Tour',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: XPTour,
    defaultSize: {
      width: 500,
      height: 350,
    },
    minSize: {
      width: 420,
      height: 300,
    },
    defaultOffset: {
      x: 180,
      y: 90,
    },
    // resizable is required for the tour to maximize itself to fullscreen.
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "xpTour": {
    icon: '/icons/xp/tray/xptour.png',
    title: 'Tour Windows XP',
    component: XPTour,
  },
  },
  catalogTargets: {
    "xpTour": "Windows XP Tour"
  },
  categories: {
    "Windows XP Tour": "system"
  },
  startMenu: {
    "tour": {
    type: 'program',
    appKey: 'Windows XP Tour',
    icon: '/icons/xp/tray/xptour.png',
    title: 'Tour Windows XP',
    description: 'Take a tour of Windows XP',
  },
  },
};
