import { lazy } from 'react';

const CommandAndConquer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Command & Conquer": {
    header: {
      icon: '/icons/games/command-and-conquer.ico',
      title: 'Command & Conquer',
      buttons: ['minimize', 'close'],
    },
    component: CommandAndConquer,
    defaultSize: {
      width: 646,
      height: 566,
    },
    defaultOffset: {
      x: 100,
      y: 20,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "commandAndConquer": {
    icon: '/icons/games/command-and-conquer.ico',
    title: 'Command & Conquer',
    component: CommandAndConquer,
  },
  },
  catalogTargets: {
    "commandAndConquer": "Command & Conquer"
  },
  categories: {
    "Command & Conquer": "game"
  },
  startMenu: {
    "commandAndConquer": {
    type: 'program',
    appKey: 'Command & Conquer',
    icon: '/icons/games/command-and-conquer.ico',
    title: 'Command & Conquer',
    description: 'Classic real-time strategy',
  },
  },
};
