import { lazy } from 'react';

const OutlookExpress = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Outlook Express": {
    header: {
      icon: "/icons/outlook/outlook.png",
      title: 'Outlook Express',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: OutlookExpress,
    defaultSize: {
      width: 708,
      height: 534,
    },
    defaultOffset: {
      x: 140,
      y: 140,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "outlookExpress": {
    icon: "/icons/outlook/outlook.png",
    title: 'Outlook Express',
    component: OutlookExpress,
  },
  },
  catalogTargets: {
    "outlookExpress": "Outlook Express"
  },
  categories: {
    "Outlook Express": "internet"
  },
};
