import { lazy } from 'react';

const Solitaire = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Solitaire": {
    header: {
      icon: '/icons/solitaire-icon.png',
      title: 'Solitaire',
      buttons: ['minimize', 'close'],
    },
    component: Solitaire,
    defaultSize: {
      width: 680,
      height: 490,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "solitaire": {
    icon: '/icons/solitaire-icon.png',
    title: 'Solitaire',
    component: Solitaire,
  },
  },
  catalogTargets: {
    "solitaire": "Solitaire"
  },
  categories: {
    "Solitaire": "game"
  },
};
