import { lazy } from 'react';

const Notepad = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Notepad": {
    header: {
      icon: "/icons/xp/Notepad.png",
      title: 'Untitled - Notepad',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Notepad,
    defaultSize: {
      width: 500,
      height: 400,
    },
    defaultOffset: {
      x: 180,
      y: 80,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "notepad": {
    icon: "/icons/xp/Notepad.png",
    title: 'Notepad',
    component: Notepad,
  },
  },
  catalogTargets: {
    "notepad": "Notepad"
  },
  categories: {
    "Notepad": "accessory"
  },
};
