import { lazy } from 'react';

const StarCraft = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "StarCraft": {
    header: {
      icon: '/icons/games/starcraft.png',
      title: 'StarCraft',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: StarCraft,
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 140,
      y: 70,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "starcraft": {
    icon: '/icons/games/starcraft.png',
    title: 'StarCraft',
    component: StarCraft,
  },
  },
  catalogTargets: {
    "starcraft": "StarCraft"
  },
  categories: {
    "StarCraft": "game"
  },
  startMenu: {
    "starcraft": {
    type: 'program',
    appKey: 'StarCraft',
    icon: '/icons/games/starcraft.png',
    title: 'StarCraft',
    description: 'Blizzard real-time strategy',
  },
  },
};
