import { lazy } from 'react';

const RedAlert2 = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Red Alert 2": {
    header: {
      icon: '/icons/games/red-alert2.png',
      title: 'Command & Conquer: Red Alert 2',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: RedAlert2,
    defaultSize: {
      width: 900,
      height: 550,
    },
    defaultOffset: {
      x: 80,
      y: 20,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "redAlert2": {
    icon: '/icons/games/red-alert2.png',
    title: 'C&C: Red Alert 2',
    component: RedAlert2,
  },
  },
  catalogTargets: {
    "redAlert2": "Red Alert 2"
  },
  categories: {
    "Red Alert 2": "game"
  },
  startMenu: {
    "redAlert2": {
    type: 'program',
    appKey: 'Red Alert 2',
    icon: '/icons/games/red-alert2.png',
    title: 'C&C: Red Alert 2',
    description: 'HTML5 port - Work in progress',
  },
  },
};
