import { lazy } from 'react';

const QQPenguin = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "QQ Penguin": {
    header: {
      icon: '/icons/qqpet.ico',
      title: 'QQ Pet',
      invisible: true,
    },
    component: QQPenguin,
    defaultSize: {
      width: 0,
      height: 0,
    },
    defaultOffset: {
      x: 0,
      y: 0,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "qqPenguin": {
    icon: '/icons/qqpet.ico',
    title: 'QQ Pet',
    component: QQPenguin,
  },
  },
  catalogTargets: {
    "qqPenguin": "QQ Penguin"
  },
  categories: {
    "QQ Penguin": "game"
  },
  startMenu: {
    "qqPenguin": {
    type: 'program',
    appKey: 'QQ Penguin',
    icon: '/icons/qqpet.ico',
    title: 'QQ Pet',
    description: 'Virtual pet app',
  },
  },
};
