import { lazy } from 'react';

const CharacterMap = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Character Map": {
    header: {
      icon: '/icons/xp/font.png',
      title: 'Character Map',
      buttons: ['minimize', 'close'],
    },
    component: CharacterMap,
    defaultSize: {
      width: 450,
      height: 470,
    },
    minSize: {
      width: 370,
      height: 350,
    },
    defaultOffset: {
      x: 180,
      y: 90,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Character Map": "accessory"
  },
};
