import { lazy } from 'react';

const LegoIsland = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "LEGO Island": {
    header: {
      icon: '/icons/games/lego-island.webp',
      title: 'LEGO Island',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: LegoIsland,
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "legoIsland": {
    icon: '/icons/games/lego-island.webp',
    title: 'LEGO Island',
    component: LegoIsland,
  },
  },
  catalogTargets: {
    "legoIsland": "LEGO Island"
  },
  categories: {
    "LEGO Island": "game"
  },
};
