import { lazy } from 'react';

const NewMessage = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Contact": {
    header: {
      icon: '/icons/outlook/write.png',
      title: 'New Message',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: NewMessage,
    defaultSize: {
      width: 640,
      height: 480,
    },
    defaultOffset: {
      x: 150,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  "New Message": {
    header: {
      icon: '/icons/outlook/write.png',
      title: 'New Message',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: NewMessage,
    defaultSize: {
      width: 640,
      height: 480,
    },
    defaultOffset: {
      x: 180,
      y: 80,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "contact": {
    icon: '/icons/outlook/write.png',
    title: 'Contact',
    component: NewMessage,
  },
  },
  catalogTargets: {
    "contact": "Contact"
  },
  categories: {
    "Contact": "portfolio"
  },
};
