import { lazy } from 'react';

const Resume = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {

  },
  icons: {
  "resume": {
    icon: '/icons/resume.webp',
    title: 'Resume',
    component: Resume,
  },
  },
  catalogTargets: {
    "resume": "Resume"
  },
  categories: {},
};
