import { lazy } from 'react';

const IframeApp = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Installed App": {
    header: {
      icon: '/icons/xp/Programs.png',
      title: 'Web App',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: IframeApp,
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  "Doom": {
    header: {
      icon: "/icons/games/doom.png",
      title: 'Doom',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: IframeApp,
    injectProps: {
      name: 'Doom',
      icon: "/icons/games/doom.png",
      url: 'https://mrdoob.github.io/three-doom/',
      allow: 'clipboard-read; clipboard-write; fullscreen; pointer-lock; gamepad',
    },
    defaultSize: {
      width: 900,
      height: 650,
    },
    defaultOffset: {
      x: 80,
      y: 30,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  "Quake": {
    header: {
      icon: "/icons/games/quake.ico",
      title: 'Quake',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: IframeApp,
    injectProps: {
      name: 'Quake',
      icon: "/icons/games/quake.ico",
      url: 'https://mrdoob.github.io/three-quake/',
      allow: 'clipboard-read; clipboard-write; fullscreen; pointer-lock; gamepad',
    },
    defaultSize: {
      width: 900,
      height: 650,
    },
    defaultOffset: {
      x: 100,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "doom": {
    icon: "/icons/games/doom.png",
    title: 'Doom',
    component: IframeApp,
  },
  "quake": {
    icon: "/icons/games/quake.ico",
    title: 'Quake',
    component: IframeApp,
  },
  },
  catalogTargets: {
    "doom": "Doom",
    "quake": "Quake"
  },
  categories: {
    "Doom": "game",
    "Quake": "game"
  },
};
