import { lazy } from 'react';

const MicrosoftWord = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Microsoft Word": {
    header: {
      icon: "/icons/xp/MSWord.png",
      title: 'Microsoft Word',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: MicrosoftWord,
    defaultSize: {
      width: 900,
      height: 700,
    },
    minSize: {
      width: 500,
      height: 400,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Microsoft Word": "accessory"
  },
  startMenu: {
    "microsoftWord": {
    type: 'program',
    appKey: 'Microsoft Word',
    icon: '/icons/xp/MSWord.png',
    title: 'Microsoft Word',
    description: 'Word processor',
  },
  },
};
