import { lazy } from 'react';

const HelpAndSupport = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Help and Support": {
    header: {
      icon: "/icons/help.png",
      title: 'Help and Support Center',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: HelpAndSupport,
    defaultSize: {
      width: 808,
      height: 584,
    },
    defaultOffset: {
      x: 80,
      y: 80,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "helpAndSupport": {
    icon: "/icons/help.png",
    title: 'Help and Support',
    component: HelpAndSupport,
  },
  },
  catalogTargets: {
    "helpAndSupport": "Help and Support"
  },
  categories: {
    "Help and Support": "system"
  },
  startMenu: {
    "help": {
    type: 'program',
    appKey: 'Help and Support',
    icon: '/icons/help.png',
    title: 'Help and Support',
    description: null,
  },
  },
};
