import { lazy } from 'react';

const SpiderSolitaire = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Spider Solitaire": {
    header: {
      icon: '/icons/spider-solitaire-icon.webp',
      title: 'Spider Solitaire',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: SpiderSolitaire,
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 80,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "spiderSolitaire": {
    icon: '/icons/spider-solitaire-icon.webp',
    title: 'Spider Solitaire',
    component: SpiderSolitaire,
  },
  },
  catalogTargets: {
    "spiderSolitaire": "Spider Solitaire"
  },
  categories: {
    "Spider Solitaire": "game"
  },
  startMenu: {
    "spiderSolitaire": {
    type: 'program',
    appKey: 'Spider Solitaire',
    icon: '/icons/spider-solitaire-icon.webp',
    title: 'Spider Solitaire',
    description: null,
  },
  },
};
