import { lazy } from 'react';

const TaskbarProperties = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Taskbar Properties": {
    header: {
      icon: '/icons/xp/DisplayProperties.png',
      title: 'Taskbar and Start Menu Properties',
      buttons: ['close'],
    },
    component: TaskbarProperties,
    defaultSize: {
      width: 408,
      height: 480,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Taskbar Properties": "system"
  },
};
