import { lazy } from 'react';

const OpenWith = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Open With": {
    header: {
      icon: '/icons/xp/Default.png',
      title: 'Open With',
      buttons: ['close'],
    },
    component: OpenWith,
    defaultSize: {
      width: 420,
      height: 'auto',
    },
    defaultOffset: {
      x: 250,
      y: 150,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Open With": "utility"
  },
};
