import { lazy } from 'react';

const SoundsAndAudioDevices = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Sounds and Audio Devices": {
    header: {
      icon: "/icons/xp/speech.png",
      title: 'Sounds and Audio Devices Properties',
      buttons: ['close'],
    },
    component: SoundsAndAudioDevices,
    defaultSize: {
      width: 436,
      height: 470,
    },
    defaultOffset: {
      x: 190,
      y: 90,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "soundsAndAudioDevices": {
    icon: "/icons/xp/speech.png",
    title: 'Sounds and Audio Devices',
    component: SoundsAndAudioDevices,
  },
  },
  catalogTargets: {
    "soundsAndAudioDevices": "Sounds and Audio Devices"
  },
  categories: {
    "Sounds and Audio Devices": "system"
  },
};
