import { lazy } from 'react';

const Coder = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Code Editor": {
    header: {
      icon: "/apps/openlair-viewer/static/images/icon/coder.png",
      title: 'Untitled - Code Editor',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Coder,
    defaultSize: {
      width: 720,
      height: 500,
    },
    minSize: {
      width: 420,
      height: 300,
    },
    defaultOffset: {
      x: 160,
      y: 70,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "coder": {
    icon: "/apps/openlair-viewer/static/images/icon/coder.png",
    title: 'Code Editor',
    component: Coder,
  },
  },
  catalogTargets: {
    "coder": "Code Editor"
  },
  categories: {
    "Code Editor": "accessory"
  },
};
