import { lazy } from 'react';

const InternetExplorer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Internet Explorer": {
    header: {
      icon: "/icons/xp/InternetExplorer6.png",
      title: 'Internet Explorer',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: InternetExplorer,
    defaultSize: {
      width: 900,
      height: 600,
    },
    defaultOffset: {
      x: 80,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "internetExplorer": {
    icon: "/icons/xp/InternetExplorer6.png",
    title: 'Internet Explorer',
    component: InternetExplorer,
  },
  },
  catalogTargets: {
    "internetExplorer": "Internet Explorer"
  },
  categories: {
    "Internet Explorer": "internet"
  },
  startMenu: {
    "internetExplorer": {
    type: 'program',
    appKey: 'Internet Explorer',
    icon: '/icons/xp/InternetExplorer6.png',
    title: 'Internet Explorer',
    description: 'Browse the web',
  },
  },
};
