import { lazy } from 'react';

const ImageViewer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Image Viewer": {
    header: {
      icon: '/apps/openlair-viewer/static/images/icon/viewer.png',
      title: 'Windows Picture and Fax Viewer',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: ImageViewer,
    defaultSize: {
      width: 700,
      height: 540,
    },
    defaultOffset: {
      x: 120,
      y: 70,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "imageViewer": {
    icon: '/apps/openlair-viewer/static/images/icon/viewer.png',
    title: 'Windows Picture and Fax Viewer',
    component: ImageViewer,
  },
  },
  catalogTargets: {
    "imageViewer": "Image Viewer"
  },
  categories: {
    "Image Viewer": "media"
  },
  startMenu: {
    "imageViewer": {
    type: 'program',
    appKey: 'Image Viewer',
    icon: '/apps/openlair-viewer/static/images/icon/viewer.png',
    title: 'Windows Picture and Fax Viewer',
    description: 'View images and photos',
  },
  },
};
