import { lazy } from 'react';

const MessageBox = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Message Box": {
    header: {
      icon: '/icons/xp/Critical.png',
      title: 'Windows',
      buttons: ['close'],
    },
    component: MessageBox,
    defaultSize: {
      width: 420,
      height: 'auto',
    },
    defaultOffset: {
      x: 300,
      y: 200,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {},
};
