import { lazy } from 'react';

const Run = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Run": {
    header: {
      icon: '/icons/luna/run.png',
      title: 'Run',
      buttons: ['close'],
    },
    component: Run,
    defaultSize: {
      width: 400,
      height: 'auto',
    },
    defaultOffset: {
      x: 200,
      y: 200,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Run": "utility"
  },
};
