import { lazy } from 'react';

const DiskDefrag = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Disk Defragmenter": {
    header: {
      icon: '/icons/xp/DiskDefrag.png',
      title: 'Disk Defragmenter',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: DiskDefrag,
    defaultSize: {
      width: 640,
      height: 480,
    },
    defaultOffset: {
      x: 150,
      y: 80,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Disk Defragmenter": "system"
  },
  startMenu: {
    "diskDefrag": {
    type: 'program',
    appKey: 'Disk Defragmenter',
    icon: '/icons/xp/DiskDefrag.png',
    title: 'Disk Defragmenter',
    description: 'Defragment your hard drive',
  },
  },
};
