import { lazy } from 'react';

const RuneScape = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "RuneScape Classic": {
    header: {
      icon: '/icons/runescape-icon.png',
      title: 'RuneScape Classic - Offline',
      buttons: ['minimize', 'close'],
    },
    component: RuneScape,
    defaultSize: {
      width: 532,
      height: 394,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "runescape": {
    icon: '/icons/runescape-icon.png',
    title: 'RuneScape Classic',
    component: RuneScape,
  },
  },
  catalogTargets: {
    "runescape": "RuneScape Classic"
  },
  categories: {
    "RuneScape Classic": "game"
  },
  startMenu: {
    "runescape": {
    type: 'program',
    appKey: 'RuneScape Classic',
    icon: '/icons/runescape-icon.png',
    title: 'RuneScape Classic',
    description: 'Offline singleplayer RSC',
  },
  },
};
