import { lazy } from 'react';

const Minesweeper = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Minesweeper": {
    header: {
      icon: "/icons/xp/Minesweeper.png",
      title: 'Minesweeper',
      buttons: ['minimize', 'close'],
    },
    component: Minesweeper,
    defaultSize: {
      width: 162,
      height: 0,
    },
    defaultOffset: {
      x: 150,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "minesweeper": {
    icon: "/icons/xp/Minesweeper.png",
    title: 'Minesweeper',
    component: Minesweeper,
  },
  },
  catalogTargets: {
    "minesweeper": "Minesweeper"
  },
  categories: {
    "Minesweeper": "game"
  },
};
