import { lazy } from 'react';

const RegistryEditor = lazy(() => import('./index.jsx'));
const RegistryEditValueDialog = lazy(() => import('./EditValueDialog'));
const RegistryNewValueDialog = lazy(() => import('./NewValueDialog'));
const RegistryNewKeyDialog = lazy(() => import('./NewKeyDialog'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Registry Editor": {
    header: {
      icon: '/icons/luna/regedit.ico',
      title: 'Registry Editor',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: RegistryEditor,
    defaultSize: {
      width: 750,
      height: 500,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  "Registry Editor - Edit Value": {
    header: {
      icon: '/icons/luna/regedit.ico',
      title: 'Edit String',
      buttons: ['close'],
    },
    component: RegistryEditValueDialog,
    defaultSize: {
      width: 380,
      height: 220,
    },
    defaultOffset: {
      x: 250,
      y: 180,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  "Registry Editor - New Value": {
    header: {
      icon: '/icons/luna/regedit.ico',
      title: 'New Value',
      buttons: ['close'],
    },
    component: RegistryNewValueDialog,
    defaultSize: {
      width: 380,
      height: 220,
    },
    defaultOffset: {
      x: 270,
      y: 200,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  "Registry Editor - New Key": {
    header: {
      icon: '/icons/luna/regedit.ico',
      title: 'New Key',
      buttons: ['close'],
    },
    component: RegistryNewKeyDialog,
    defaultSize: {
      width: 380,
      height: 170,
    },
    defaultOffset: {
      x: 270,
      y: 200,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "registryEditor": {
    icon: '/icons/luna/regedit.ico',
    title: 'Registry Editor',
    component: RegistryEditor,
  },
  },
  catalogTargets: {
    "registryEditor": "Registry Editor"
  },
  categories: {
    "Registry Editor": "system"
  },
  startMenu: {
    "registryEditor": {
    type: 'program',
    appKey: 'Registry Editor',
    icon: '/icons/luna/regedit.ico',
    title: 'Registry Editor',
    description: 'Edit the Windows registry',
  },
  },
};
