import { lazy } from 'react';

const Calculator = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Calculator": {
    header: {
      icon: "/icons/xp/Calculator.png",
      title: 'Calculator',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Calculator,
    defaultSize: {
      width: 250,
      height: 310,
    },
    minSize: {
      width: 250,
      height: 310,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "calculator": {
    icon: "/icons/xp/Calculator.png",
    title: 'Calculator',
    component: Calculator,
  },
  },
  catalogTargets: {
    "calculator": "Calculator"
  },
  categories: {
    "Calculator": "accessory"
  },
};
