import { lazy } from 'react';

const DateTimeProperties = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Date and Time Properties": {
    header: {
      icon: '/icons/xp/DateTime.png',
      title: 'Date and Time Properties',
      buttons: ['close'],
    },
    component: DateTimeProperties,
    defaultSize: {
      width: 400,
      height: 380,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {},
};
