import { lazy } from 'react';

const SystemProperties = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "System Properties": {
    header: {
      icon: "/icons/xp/system.png",
      title: 'System Properties',
      buttons: ['close'],
    },
    component: SystemProperties,
    defaultSize: {
      width: 408,
      height: 435,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "systemProperties": {
    icon: "/icons/xp/system.png",
    title: 'System Properties',
    component: SystemProperties,
  },
  },
  catalogTargets: {
    "systemProperties": "System Properties"
  },
  categories: {
    "System Properties": "system"
  },
};
