import { lazy } from 'react';

const VolumeControl = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Volume Control": {
    header: {
      icon: '/icons/luna/volume_on.png',
      title: 'Volume Control',
      buttons: ['minimize', 'close'],
    },
    component: VolumeControl,
    defaultSize: {
      width: 160,
      height: 300,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Volume Control": "system"
  },
  startMenu: {
    "volumeControl": {
    type: 'program',
    appKey: 'Volume Control',
    icon: '/icons/luna/volume_on.png',
    title: 'Volume Control',
    description: 'Adjust system volume',
  },
  },
};
