import { lazy } from 'react';

const UserAccounts = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "User Accounts": {
    header: {
      icon: "/icons/xp/UserAccounts.png",
      title: 'User Accounts',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: UserAccounts,
    defaultSize: {
      width: 708,
      height: 534,
    },
    defaultOffset: {
      x: 80,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "userAccounts": {
    icon: "/icons/xp/UserAccounts.png",
    title: 'User Accounts',
    component: UserAccounts,
  },
  },
  catalogTargets: {
    "userAccounts": "User Accounts"
  },
  categories: {
    "User Accounts": "system"
  },
  startMenu: {
    "userAccounts": {
    type: 'program',
    appKey: 'User Accounts',
    icon: '/icons/xp/UserAccounts.png',
    title: 'User Accounts',
    description: 'Manage user accounts',
  },
  },
};
