import { lazy } from 'react';

const Properties = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Properties": {
    header: {
      icon: '/icons/xp/DisplayProperties.png',
      title: 'Properties',
      buttons: ['close'],
    },
    component: Properties,
    defaultSize: {
      width: 350,
      height: 460,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Properties": "utility"
  },
};
