import { lazy } from 'react';

const TransferWizard = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Transfer Wizard": {
    header: {
      icon: "/icons/xp/tray/migrate.png",
      title: 'Files and Settings Transfer Wizard',
      buttons: ['help', 'minimize', 'maximize', 'close'],
    },
    component: TransferWizard,
    defaultSize: {
      width: 500,
      height: 390,
    },
    defaultOffset: {
      x: 120,
      y: 120,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "transferWizard": {
    icon: "/icons/xp/tray/migrate.png",
    title: 'Transfer Wizard',
    component: TransferWizard,
  },
  },
  catalogTargets: {
    "transferWizard": "Transfer Wizard"
  },
  categories: {
    "Transfer Wizard": "system"
  },
  startMenu: {
    "transferWizard": {
    type: 'program',
    appKey: 'Transfer Wizard',
    icon: '/icons/xp/tray/migrate.png',
    title: 'Files and Settings Transfer Wizard',
    description: 'Transfer your environment',
  },
  },
};
