import { lazy } from 'react';

const Wordpad = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "WordPad": {
    header: {
      icon: "/icons/xp/wordpad.png",
      title: 'Document - WordPad',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Wordpad,
    defaultSize: {
      width: 608,
      height: 534,
    },
    defaultOffset: {
      x: 120,
      y: 60,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "wordpad": {
    icon: "/icons/xp/wordpad.png",
    title: 'WordPad',
    component: Wordpad,
  },
  },
  catalogTargets: {
    "wordpad": "WordPad"
  },
  categories: {
    "WordPad": "accessory"
  },
};
