import { lazy } from 'react';

const ESheep = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "eSheep": {
    header: {
      icon: '/icons/esheep.png',
      title: 'eSheep',
      invisible: true,
      noFooterWindow: true,
    },
    component: ESheep,
    defaultSize: {
      width: 0,
      height: 0,
    },
    defaultOffset: {
      x: 0,
      y: 0,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "eSheep": "game"
  },
};
