import { lazy } from 'react';

const DisplayProperties = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Display Properties": {
    header: {
      icon: "/icons/xp/DisplayProperties.png",
      title: 'Display Properties',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: DisplayProperties,
    defaultSize: {
      width: 500,
      height: 640,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "displayProperties": {
    icon: "/icons/xp/DisplayProperties.png",
    title: 'Display Properties',
    component: DisplayProperties,
  },
  },
  catalogTargets: {
    "displayProperties": "Display Properties"
  },
  categories: {
    "Display Properties": "system"
  },
};
