import { lazy } from 'react';

const FlashPlayer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Adobe Flash Player": {
    header: {
      icon: "/icons/flash/flash_player.png",
      title: 'Adobe Flash Player',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: FlashPlayer,
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "flashPlayer": {
    icon: "/icons/flash/flash_player.png",
    title: 'Adobe Flash Player',
    component: FlashPlayer,
  },
  },
  catalogTargets: {
    "flashPlayer": "Adobe Flash Player"
  },
  categories: {
    "Adobe Flash Player": "media"
  },
  startMenu: {
    "flashPlayer": {
    type: 'program',
    appKey: 'Adobe Flash Player',
    icon: '/icons/flash/flash_player.png',
    title: 'Adobe Flash Player',
    description: 'Play Flash content with Ruffle',
  },
  },
};
