import { lazy } from 'react';

const ErrorDialog = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Error Dialog": {
    header: {
      icon: '/icons/xp/Error.png',
      title: 'Error',
      buttons: ['close'],
    },
    component: ErrorDialog,
    defaultSize: {
      width: 420,
      height: 'auto',
    },
    defaultOffset: {
      x: 300,
      y: 200,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
    mobileFullscreen: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {},
};
