import { lazy } from 'react';

const AdobeReader = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Resume": {
    header: {
      icon: '/icons/pdf/acroaum_grp107_lang1033.ico',
      title: 'Adobe Reader - [CV.pdf]',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: AdobeReader,
    injectProps: {
      pdfPath: '/CV.pdf',
      pdfName: 'CV.pdf',
    },
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 120,
      y: 30,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  "Adobe Reader": {
    header: {
      icon: "/icons/pdf/acroaum_grp107_lang1033.ico",
      title: 'Adobe Reader',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: AdobeReader,
    defaultSize: {
      width: 900,
      height: 650,
    },
    defaultOffset: {
      x: 60,
      y: 30,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "adobeReader": {
    icon: "/icons/pdf/acroaum_grp107_lang1033.ico",
    title: 'Adobe Reader',
    component: AdobeReader,
  },
  },
  catalogTargets: {
    "adobeReader": "Adobe Reader"
  },
  categories: {
    "Resume": "portfolio",
    "Adobe Reader": "utility"
  },
  startMenu: {
    "resume": {
    type: 'program',
    appKey: 'Resume',
    icon: '/icons/pdf/PDF.ico',
    title: 'My Resume',
    description: 'View my CV',
  },
    "adobeReader": {
    type: 'program',
    appKey: 'Adobe Reader',
    icon: '/icons/pdf/acroaum_grp107_lang1033.ico',
    title: 'Adobe Reader',
    description: 'View PDF files',
  },
  },
};
