import { lazy } from 'react';

const TaskManager = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Task Manager": {
    header: {
      icon: '/icons/xp/taskmgr.png',
      title: 'Windows Task Manager',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: TaskManager,
    defaultSize: {
      width: 400,
      height: 450,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "taskManager": {
    icon: '/icons/xp/taskmgr.png',
    title: 'Task Manager',
    component: TaskManager,
  },
  },
  catalogTargets: {
    "taskManager": "Task Manager"
  },
  categories: {
    "Task Manager": "system"
  },
};
