import { lazy } from 'react';

const MediaPlayerClassic = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Windows Media Player Classic": {
    header: {
      icon: "/icons/xp/WindowsMediaPlayer9.png",
      title: 'Windows Media Player',
      buttons: ['minimize', 'maximize', 'close'],
      invisible: true,
    },
    component: MediaPlayerClassic,
    defaultSize: {
      width: 640,
      height: 533,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "mediaPlayerClassic": {
    icon: "/icons/xp/WindowsMediaPlayer9.png",
    title: 'Windows Media Player Classic',
    component: MediaPlayerClassic,
  },
  },
  catalogTargets: {
    "mediaPlayerClassic": "Windows Media Player Classic"
  },
  categories: {
    "Windows Media Player Classic": "media"
  },
};
