import { lazy } from 'react';

const MSNMessenger = lazy(() => import('./index.jsx'));
const MSNMessengerConversation = lazy(() => import('./ConversationApp'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "MSN Messenger": {
    header: {
      icon: '/icons/xp/messenger.png',
      title: 'MSN Messenger',
      buttons: ['minimize', 'maximize', 'close'],
      invisible: true,
    },
    component: MSNMessenger,
    defaultSize: {
      width: 280,
      height: 540,
    },
    minSize: {
      width: 280,
      height: 540,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  "MSN Messenger Conversation": {
    header: {
      icon: '/icons/xp/messenger.png',
      title: 'MSN Messenger Conversation',
      buttons: ['minimize', 'maximize', 'close'],
      invisible: true,
    },
    component: MSNMessengerConversation,
    defaultSize: {
      width: 560,
      height: 540,
    },
    minSize: {
      width: 560,
      height: 540,
    },
    defaultOffset: {
      x: 140,
      y: 80,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "msnMessenger": {
    icon: '/icons/xp/messenger.png',
    title: 'MSN Messenger',
    component: MSNMessenger,
  },
  },
  catalogTargets: {
    "msnMessenger": "MSN Messenger"
  },
  categories: {
    "MSN Messenger": "internet"
  },
  startMenu: {
    "msnMessenger": {
    type: 'program',
    appKey: 'MSN Messenger',
    icon: '/icons/xp/messenger.png',
    title: 'MSN Messenger',
    description: 'Chat with Chatango',
  },
  },
};
