import { lazy } from 'react';

const OpenFileDialog = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Open File": {
    header: {
      icon: '/icons/xp/FolderOpened.png',
      title: 'Open',
      buttons: ['close'],
    },
    component: OpenFileDialog,
    defaultSize: {
      width: 500,
      height: 400,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {},
};
