import { lazy } from 'react';

const WorldOfWarcraft = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "World of Warcraft": {
    header: {
      icon: "/icons/games/wow.webp",
      title: 'World of Warcraft',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: WorldOfWarcraft,
    defaultSize: {
      width: 900,
      height: 650,
    },
    defaultOffset: {
      x: 80,
      y: 30,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "worldOfWarcraft": {
    icon: "/icons/games/wow.webp",
    title: 'World of Warcraft',
    component: WorldOfWarcraft,
  },
  },
  catalogTargets: {
    "worldOfWarcraft": "World of Warcraft"
  },
  categories: {
    "World of Warcraft": "game"
  },
};
