import { lazy } from 'react';

const Paint = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Paint": {
    header: {
      icon: "/icons/xp/Paint.png",
      title: 'Paint',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Paint,
    defaultSize: {
      width: 800,
      height: 600,
    },
    defaultOffset: {
      x: 50,
      y: 30,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
    mobileAvailable: false,  // Paint requires mouse precision
  },
  },
  icons: {
  "paint": {
    icon: "/icons/xp/Paint.png",
    title: 'Paint',
    component: Paint,
  },
  },
  catalogTargets: {
    "paint": "Paint"
  },
  categories: {
    "Paint": "accessory"
  },
};
