import { lazy } from 'react';

const BackupWizard = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Backup Wizard": {
    header: {
      icon: "/icons/xp/tray/backup.png",
      title: 'Backup or Restore Wizard',
      buttons: ['help', 'minimize', 'maximize', 'close'],
    },
    component: BackupWizard,
    defaultSize: {
      width: 500,
      height: 390,
    },
    defaultOffset: {
      x: 100,
      y: 100,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "backupWizard": {
    icon: "/icons/xp/tray/backup.png",
    title: 'Backup Wizard',
    component: BackupWizard,
  },
  },
  catalogTargets: {
    "backupWizard": "Backup Wizard"
  },
  categories: {
    "Backup Wizard": "system"
  },
  startMenu: {
    "backupWizard": {
    type: 'program',
    appKey: 'Backup Wizard',
    icon: '/icons/xp/tray/backup.png',
    title: 'Backup',
    description: 'Backup or restore files',
  },
  },
};
