import { lazy } from 'react';

const WinHelp = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Windows Help": {
    header: {
      icon: "/icons/help.png",
      title: 'Windows Help',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: WinHelp,
    defaultSize: {
      width: 680,
      height: 520,
    },
    defaultOffset: {
      x: 100,
      y: 60,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Windows Help": "system"
  },
};
