import { lazy } from 'react';

const RecycleBin = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Recycle Bin": {
    header: {
      icon: "/icons/xp/RecycleBinempty.png",
      title: 'Recycle Bin',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: RecycleBin,
    defaultSize: {
      width: 660,
      height: 500,
    },
    defaultOffset: {
      x: 140,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "recycleBin": {
    icon: "/icons/xp/RecycleBinempty.png",
    title: 'Recycle Bin',
    component: RecycleBin,
  },
  },
  catalogTargets: {
    "recycleBin": "Recycle Bin"
  },
  categories: {
    "Recycle Bin": "system"
  },
};
