import { lazy } from 'react';

const FontViewer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Font Viewer": {
    header: {
      icon: "/icons/xp/font.png",
      title: 'Font Preview',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: FontViewer,
    defaultSize: {
      width: 708,
      height: 534,
    },
    defaultOffset: {
      x: 50,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Font Viewer": "utility"
  },
};
