import { lazy } from 'react';

const MicrosoftExcel = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Microsoft Excel": {
    header: {
      icon: "/icons/xp/MSExcel.gif",
      title: 'Microsoft Excel',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: MicrosoftExcel,
    defaultSize: {
      width: 1000,
      height: 700,
    },
    minSize: {
      width: 600,
      height: 400,
    },
    defaultOffset: {
      x: 80,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Microsoft Excel": "accessory"
  },
  startMenu: {
    "microsoftExcel": {
    type: 'program',
    appKey: 'Microsoft Excel',
    icon: '/icons/xp/MSExcel.gif',
    title: 'Microsoft Excel',
    description: 'Spreadsheet editor',
  },
  },
};
