import { lazy } from 'react';

const Winamp = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Winamp": {
    header: {
      icon: '/icons/winamp.png',
      title: 'Winamp',
      invisible: true,
    },
    component: Winamp,
    defaultSize: {
      width: 0,
      height: 0,
    },
    defaultOffset: {
      x: 0,
      y: 0,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "winamp": {
    icon: '/icons/winamp.png',
    title: 'Winamp',
    component: Winamp,
  },
  },
  catalogTargets: {
    "winamp": "Winamp"
  },
  categories: {
    "Winamp": "media"
  },
};
