import { lazy } from 'react';

const BlueScreenOfDeath = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Blue Screen of Death": {
    header: {
      icon: '/icons/luna/dialog_error.png',
      title: 'Blue Screen of Death',
      invisible: true,
      noFooterWindow: true,
    },
    component: BlueScreenOfDeath,
    defaultSize: {
      width: 0,
      height: 0,
    },
    defaultOffset: {
      x: 0,
      y: 0,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "blueScreenOfDeath": {
    icon: '/icons/luna/dialog_error.png',
    title: 'Blue Screen of Death',
    component: BlueScreenOfDeath,
  },
  },
  catalogTargets: {
    "blueScreenOfDeath": "Blue Screen of Death"
  },
  categories: {
    "Blue Screen of Death": "game"
  },
  startMenu: {
    "blueScreenOfDeath": {
    type: 'program',
    appKey: 'Blue Screen of Death',
    icon: '/icons/luna/dialog_error.png',
    title: 'Blue Screen of Death',
    description: 'Trigger a fake crash and reboot',
  },
  },
};
