// File type descriptions for details view
export const FILE_TYPES = {
  exe: 'Application',
  dll: 'Dynamic Link Library',
  sys: 'System File',
  bat: 'Batch File',
  cmd: 'Command Script',
  lnk: 'Shortcut File',
  txt: 'Text Document',
  doc: 'Microsoft Word Document',
  docx: 'Microsoft Word Document',
  xls: 'Microsoft Excel Spreadsheet',
  xlsx: 'Microsoft Excel Spreadsheet',
  ppt: 'Microsoft PowerPoint',
  pptx: 'Microsoft PowerPoint',
  pdf: 'PDF Document',
  rtf: 'Rich Text Document',
  html: 'HTML Document',
  htm: 'HTML Document',
  css: 'CSS Stylesheet',
  js: 'JavaScript File',
  json: 'JSON File',
  xml: 'XML Document',
  bmp: 'Bitmap Image',
  jpg: 'JPEG Image',
  jpeg: 'JPEG Image',
  png: 'PNG Image',
  gif: 'GIF Image',
  webp: 'WebP Image',
  svg: 'SVG Image',
  ico: 'Icon File',
  mp3: 'MP3 Audio',
  wav: 'WAV Audio',
  ogg: 'OGG Audio',
  mp4: 'MP4 Video',
  avi: 'AVI Video',
  mkv: 'MKV Video',
  mov: 'QuickTime Movie',
  wmv: 'Windows Media Video',
  webm: 'WebM Video',
  zip: 'Compressed (zipped) Folder',
  rar: 'RAR Archive',
  '7z': '7-Zip Archive',
  tar: 'TAR Archive',
  gz: 'GZip Archive',
  ini: 'Configuration Settings',
  log: 'Log File',
  md: 'Markdown Document',
};

// View mode options
export const VIEW_MODES = {
  THUMBNAILS: 'thumbnails',
  TILES: 'tiles',
  ICONS: 'icons',
  LIST: 'list',
  DETAILS: 'details',
};

// Sort options
export const SORT_OPTIONS = {
  NAME: 'name',
  SIZE: 'size',
  TYPE: 'type',
  MODIFIED: 'modified',
};
