import { lazy } from 'react';

const MyComputer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "My Computer": {
    header: {
      icon: '/icons/xp/MyComputer.png',
      title: 'My Computer',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: MyComputer,
    defaultSize: {
      width: 660,
      height: 500,
    },
    defaultOffset: {
      x: 140,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "myComputer": {
    icon: '/icons/xp/MyComputer.png',
    title: 'My Computer',
    component: MyComputer,
  },
  },
  catalogTargets: {
    "myComputer": "My Computer"
  },
  categories: {
    "My Computer": "system"
  },
};
