import { lazy } from 'react';

const SpeechProperties = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Speech Properties": {
    header: {
      icon: "/icons/xp/speech.png",
      title: 'Speech Properties',
      buttons: ['close'],
    },
    component: SpeechProperties,
    defaultSize: {
      width: 408,
      height: 540,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "speechProperties": {
    icon: "/icons/xp/speech.png",
    title: 'Speech Properties',
    component: SpeechProperties,
  },
  },
  catalogTargets: {
    "speechProperties": "Speech Properties"
  },
  categories: {
    "Speech Properties": "system"
  },
};
