import { lazy } from 'react';

const Pinball = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Pinball": {
    header: {
      icon: '/icons/pinball-icon.png',
      title: '3D Pinball for Windows - Space Cadet',
      buttons: ['minimize', 'close'],
    },
    component: Pinball,
    defaultSize: {
      width: 610,
      height: 475,
    },
    defaultOffset: {
      x: 120,
      y: 60,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
    mobileAvailable: false,  // Pinball requires keyboard controls
  },
  },
  icons: {
  "pinball": {
    icon: '/icons/pinball-icon.png',
    title: '3D Pinball',
    component: Pinball,
  },
  },
  catalogTargets: {
    "pinball": "Pinball"
  },
  categories: {
    "Pinball": "game"
  },
};
