import { lazy } from 'react';

const Projects = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Projects": {
    header: {
      icon: '/icons/projects.webp',
      title: 'My Projects',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Projects,
    defaultSize: {
      width: 750,
      height: 500,
    },
    defaultOffset: {
      x: 80,
      y: 60,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "projects": {
    icon: '/icons/projects.webp',
    title: 'Projects',
    component: Projects,
  },
  },
  catalogTargets: {
    "projects": "Projects"
  },
  categories: {
    "Projects": "portfolio"
  },
};
