import { lazy } from 'react';

const CMD = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "CMD": {
    header: {
      icon: "/icons/xp/CommandPrompt.png",
      title: 'Command Prompt',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: CMD,
    defaultSize: {
      width: 680,
      height: 400,
    },
    defaultOffset: {
      x: 100,
      y: 80,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  "Command Prompt": {
    header: {
      icon: "/icons/xp/CommandPrompt.png",
      title: 'Command Prompt',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: CMD,
    defaultSize: {
      width: 680,
      height: 400,
    },
    defaultOffset: {
      x: 100,
      y: 80,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "cmd": {
    icon: "/icons/xp/CommandPrompt.png",
    title: 'Command Prompt',
    component: CMD,
  },
  },
  catalogTargets: {
    "cmd": "Command Prompt"
  },
  categories: {
    "Command Prompt": "accessory"
  },
};
