import { lazy } from 'react';

const Installer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Add or Remove Programs": {
    header: {
      icon: '/icons/xp/programs/add.png',
      title: 'Add or Remove Programs',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Installer,
    defaultSize: {
      width: 620,
      height: 520,
    },
    defaultOffset: {
      x: 80,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  "App Installer": {
    header: {
      icon: '/icons/xp/programs/add.png',
      title: 'Add or Remove Programs',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: Installer,
    defaultSize: {
      width: 620,
      height: 520,
    },
    defaultOffset: {
      x: 80,
      y: 40,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "installer": {
    icon: '/icons/xp/programs/add.png',
    title: 'Add or Remove Programs',
    component: Installer,
  },
  },
  catalogTargets: {
    "installer": "App Installer"
  },
  categories: {
    "Add or Remove Programs": "system",
    "App Installer": "system"
  },
};
