import { lazy } from 'react';

const Wizard101 = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Wizard101": {
    header: {
      icon: '/apps/wizard101/images/icon.ico',
      title: 'Wizard101',
      buttons: ['close'],
      invisible: true,
    },
    component: Wizard101,
    defaultSize: {
      width: 810,
      height: 620,
    },
    defaultOffset: {
      x: 80,
      y: 30,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "wizard101": {
    icon: '/apps/wizard101/images/icon.ico',
    title: 'Wizard101',
    component: Wizard101,
  },
  },
  catalogTargets: {
    "wizard101": "Wizard101"
  },
  categories: {
    "Wizard101": "game"
  },
};
