import { lazy } from 'react';

const SoundRecorder = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Sound Recorder": {
    header: {
      icon: "/icons/xp/SoundRecorder.webp",
      title: 'Sound - Sound Recorder',
      buttons: ['minimize', 'close'],
    },
    component: SoundRecorder,
    defaultSize: {
      width: 280,
      height: 180,
    },
    defaultOffset: {
      x: 200,
      y: 150,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {
  "soundRecorder": {
    icon: "/icons/xp/SoundRecorder.webp",
    title: 'Sound Recorder',
    component: SoundRecorder,
  },
  },
  catalogTargets: {
    "soundRecorder": "Sound Recorder"
  },
  categories: {
    "Sound Recorder": "media"
  },
};
