import { lazy } from 'react';

const FolderOptions = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Folder Options": {
    header: {
      icon: '/icons/xp/FolderClosed.png',
      title: 'Folder Options',
      buttons: ['close'],
    },
    component: FolderOptions,
    defaultSize: {
      width: 380,
      height: 443,
    },
    defaultOffset: {
      x: 250,
      y: 120,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Folder Options": "system"
  },
};
