import { lazy } from 'react';

const BrowseForFolder = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Browse For Folder": {
    header: {
      icon: '/icons/xp/Folder.png',
      title: 'Browse For Folder',
      buttons: ['help', 'close'],
    },
    component: BrowseForFolder,
    defaultSize: {
      width: 320,
      height: 400,
    },
    defaultOffset: {
      x: 250,
      y: 120,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Browse For Folder": "utility"
  },
};
