import { lazy } from 'react';

const WinRAR = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "WinRAR": {
    header: {
      icon: '/icons/xp/RAR.png',
      title: 'WinRAR',
      buttons: ['close'],
    },
    component: WinRAR,
    defaultSize: {
      width: 280,
      height: 180,
    },
    defaultOffset: {
      x: 200,
      y: 150,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: true,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "WinRAR": "utility"
  },
};
