import { lazy } from 'react';

const MediaPlayer = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Media Player": {
    header: {
      icon: "/icons/xp/WindowsMediaPlayer9.png",
      title: 'Windows Media Player',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: MediaPlayer,
    defaultSize: {
      width: 640,
      height: 480,
    },
    defaultOffset: {
      x: 80,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
    mobileAvailable: false,  // Media Player has complex UI not suited for mobile
  },
  "Windows Media Player": {
    header: {
      icon: "/icons/xp/WindowsMediaPlayer9.png",
      title: 'Windows Media Player',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: MediaPlayer,
    defaultSize: {
      width: 640,
      height: 480,
    },
    defaultOffset: {
      x: 80,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
    mobileAvailable: false,  // Media Player has complex UI not suited for mobile
  },
  },
  icons: {
  "mediaPlayer": {
    icon: "/icons/xp/WindowsMediaPlayer9.png",
    title: 'Windows Media Player',
    component: MediaPlayer,
  },
  },
  catalogTargets: {
    "mediaPlayer": "Windows Media Player"
  },
  categories: {
    "Windows Media Player": "media"
  },
};
