import { lazy } from 'react';

const SystemInformation = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "System Information": {
    header: {
      icon: '/icons/xp/system.png',
      title: 'System Information',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: SystemInformation,
    defaultSize: {
      width: 660,
      height: 480,
    },
    defaultOffset: {
      x: 130,
      y: 60,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "systemInformation": {
    icon: '/icons/xp/system.png',
    title: 'System Information',
    component: SystemInformation,
  },
  },
  catalogTargets: {
    "systemInformation": "System Information"
  },
  categories: {
    "System Information": "system"
  },
  startMenu: {
    "systemInformation": {
    type: 'program',
    appKey: 'System Information',
    icon: '/icons/xp/system.png',
    title: 'System Information',
    description: 'View system configuration',
  },
  },
};
