import { lazy } from 'react';

const ThemeManager = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Theme Settings": {
    header: {
      icon: "/icons/xp/DisplayProperties.png",
      title: 'Theme Settings',
      buttons: ['minimize', 'close'],
    },
    component: ThemeManager,
    defaultSize: {
      width: 560,
      height: 400,
    },
    defaultOffset: {
      x: 230,
      y: 110,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Theme Settings": "system"
  },
  startMenu: {
    "themeSettings": {
    type: 'program',
    appKey: 'Theme Settings',
    icon: '/icons/xp/DisplayProperties.png',
    title: 'Theme Settings',
    description: 'Switch shell themes',
  },
  },
};
