import { lazy } from 'react';

const AboutWindows = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "About Windows": {
    header: {
      icon: '/icons/xp/system.png',
      title: 'About Windows',
      buttons: ['close'],
    },
    component: AboutWindows,
    defaultSize: {
      width: 413,
      height: 322,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "About Windows": "system"
  },
  startMenu: {
    "aboutWindows": {
    type: 'program',
    appKey: 'About Windows',
    icon: '/icons/xp/system.png',
    title: 'About Windows',
    description: 'Display Windows version information',
  },
  },
};
