import { lazy } from 'react';

const ShortcutWizard = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "Create Shortcut": {
    header: {
      icon: '/icons/xp/Shortcutoverlay.png',
      title: 'Create Shortcut',
      buttons: ['close'],
    },
    component: ShortcutWizard,
    defaultSize: {
      width: 500,
      height: 380,
    },
    defaultOffset: {
      x: 200,
      y: 100,
    },
    resizable: false,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "Create Shortcut": "utility"
  },
};
