import { lazy } from 'react';

const SystemRecovery = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "System Recovery": {
    header: {
      icon: '/icons/xp/Recovery.png',
      title: 'System Recovery',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: SystemRecovery,
    defaultSize: {
      width: 508,
      height: 334,
    },
    defaultOffset: {
      x: 140,
      y: 140,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {

  },
  catalogTargets: {},
  categories: {
    "System Recovery": "system"
  },
};
