import { lazy } from 'react';

const About = lazy(() => import('./index.jsx'));

// Auto-generated by scripts/migrate-app-manifests.mjs — describes every window,
// desktop icon, and category this folder contributes to the app registry.
export default {
  apps: {
  "About Me": {
    header: {
      icon: '/icons/about.webp',
      title: 'About Me',
      buttons: ['minimize', 'maximize', 'close'],
    },
    component: About,
    defaultSize: {
      width: 776,
      height: 556,
    },
    defaultOffset: {
      x: 100,
      y: 50,
    },
    resizable: true,
    minimized: false,
    maximized: false,
    multiInstance: false,
  },
  },
  icons: {
  "about": {
    icon: '/icons/about.webp',
    title: 'About Me',
    component: About,
  },
  },
  catalogTargets: {
    "about": "About Me"
  },
  categories: {
    "About Me": "portfolio"
  },
  startMenu: {
    "about": {
    type: 'program',
    appKey: 'About Me',
    icon: '/icons/about.webp',
    title: 'About Me',
    description: null,
  },
  },
};
